language: go
go:
- tip
before_script:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
